
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: "heart-disease-api"
        metrics_path: /metrics

        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
                - default

        relabel_configs:
          - source_labels:
              - __meta_kubernetes_pod_label_app
            regex: heart-disease-api
            action: keep

          - source_labels:
              - __meta_kubernetes_pod_container_port_number
            regex: "8000"
            action: keep

          - source_labels:
              - __meta_kubernetes_pod_ip
            target_label: pod_ip

          - source_labels:
              - __meta_kubernetes_pod_name
            target_label: pod

          - source_labels:
              - __meta_kubernetes_pod_ip
            regex: (.+)
            target_label: __address__
            replacement: $1:8000
