{
 "title": "heart-disease-dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Prediction requests over time",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(heart_disease_http_requests_total{endpoint=\"/predict\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prediction counts by class",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (prediction) (heart_disease_predictions_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average API latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(heart_disease_http_request_duration_seconds_sum{endpoint=\"/predict\"}[5m])) / sum(rate(heart_disease_http_request_duration_seconds_count{endpoint=\"/predict\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prediction processing errors",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(heart_disease_prediction_errors_total)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}