{
 "title": "heart-disease-dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Total Prediction Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(heart_disease_http_requests_total{endpoint=\"/predict\"}) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prediction counts by class",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (prediction) (heart_disease_predictions_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Prediction API Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(heart_disease_http_request_duration_seconds_sum{endpoint=\"/predict\"}[5m])) / sum(rate(heart_disease_http_request_duration_seconds_count{endpoint=\"/predict\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prediction Processing Errors",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(heart_disease_prediction_errors_total) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}